### ISSUE TITLE
PATCH FOR UPDATE IP ADDRESS 

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/TS-SQL#2]
CHANGE  IP ADDRESS IN CONFIG TYPE GENERAL TO USER RIGHTS

**Comment by DHIVYAARJUAN** [comment]
PATCH COMPLETED DELIVERED IN BELOW LINK
https://github.com/SSOMENSREPO/TS-SQL-PATCH/releases/tag/v2.6
