### ISSUE TITLE
PREPARE 2016 PUBLIC HOLIDAY SS

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/TS-SQL#3]
@krishela 

Refer the below pdf , page no 2. 
https://drive.google.com/a/ssomens.com/file/d/0B3gPZQaQ8TFTWmZKUnR0dXJLZ3M/view?ts=564491ed

Prepare like sheet name 2015 form reference

https://docs.google.com/spreadsheets/d/1MK5njSf6x5rYp0gAg7VKFPNtlV5lV7q_fNmL2FSI8hM/edit#gid=0&vpid=A1

**Comment by krishela** [comment]
# status : done 

Prepared public holiday sheet for year-2016

sheet link:

https://docs.google.com/spreadsheets/d/1j7zbAFElcJUcCrYZnXwCj7k6FcQwRYcMMr9S7L494IM/edit#gid=0&vpid=A1

**Comment by DHANDAPANISATTANATHAN** [comment]
# status: Integrated

Checked and int in prod

**Comment by DHANDAPANISATTANATHAN** [comment]
# staus : closed
